### ISSUE TITLE
[Feature request] Comment Character (#) for hotkey commenting

### ISSUE THREAD

**Issue by RuiApostolo** [ipcamit/lammps-st3#1]
Hi!

Thanks for your work, it really helps me work faster. Any chance you can update it to make sublime recognize the octothorpe as the comment character so that I could use the hotkey - default "ctrl + /"

Cheers,
Rui

**Comment by ipcamit** [comment]
I never realized there is such feature in sublime! You have no idea how much I have struggled in switching habit of shifting comment character while going from python to matlab etc! Any way i will definitely update it shortly

**Comment by RuiApostolo** [comment]
I am glad I can be of some help, since your work has definitely helped me!

Cheers,
Rui

**Comment by ipcamit** [comment]
Done! there is a new tmPreferences file which you can copy in there, which toggles '# ' for ctrl /.
This also paves way for more features in future, will see.

Thank you
